/**
 * Property-Based Tests for Surf Engine
 *
 * Feature: mvp-stumble
 * Properties 1, 2, 3, 4, 5, 6, 7
 * Validates: Requirements 1.1, 1.3, 1.4, 2.2, 2.3, 2.4, 3.2, 4.2, 4.3, 10.5, 10.6, 12.1, 12.2
 */

import { describe, it, expect } from "vitest";
import * as fc from "fast-check";
import { surf, SurfParams, SiteRow, SurfResult } from "./surf.js";

// ---------------------------------------------------------------------------
// Test Corpus Generators
// ---------------------------------------------------------------------------

const validMoods = ["useful", "learn", "waste_time", "beautiful", "think"] as const;
const validCharacters = ["modern_indie", "old_web", "retro_personal", "minimal_static"] as const;
const validStacks = ["nextjs", "hugo", "static_html", "gatsby", "11ty", "astro"] as const;
const validHosts = ["github_pages", "vercel", "neocities", "netlify", "cloudflare_pages"] as const;
const validStaticOrDynamic = ["static", "dynamic"] as const;

/** Generate a semicolon-separated mood_tags string (1-3 moods) */
const moodTagsArb = fc
  .uniqueArray(fc.constantFrom(...validMoods), { minLength: 1, maxLength: 3 })
  .map((moods) => moods.join(";"));

/** Generate a nullable provenance field */
const nullableStackArb = fc.oneof(
  fc.constant(null),
  fc.constantFrom(...validStacks)
);
const nullableHostArb = fc.oneof(
  fc.constant(null),
  fc.constantFrom(...validHosts)
);
const nullableStaticOrDynamicArb = fc.oneof(
  fc.constant(null),
  fc.constantFrom(...validStaticOrDynamic)
);

/** Generate a single SiteRow */
const siteRowArb = (id: number): fc.Arbitrary<SiteRow> =>
  fc.record({
    id: fc.constant(id),
    url: fc.constant(`https://site-${id}.example.com`),
    title: fc.constant(`Site ${id}`),
    mood_tags: moodTagsArb,
    character: fc.constantFrom(...validCharacters),
    stack: nullableStackArb,
    host: nullableHostArb,
    static_or_dynamic: nullableStaticOrDynamicArb,
    built_with: fc.constant(null),
    why_note: fc.constant("A cool site"),
    nsfw: fc.constantFrom(0, 0, 0, 0, 1) as fc.Arbitrary<number>, // 20% chance NSFW
    vibecoded: fc.constant(0),
    source: fc.constant("manual"),
    tier: fc.constant("featured"),
    added_at: fc.constant("2024-01-01T00:00:00.000Z"),
  });

/** Generate a corpus of 5-30 sites with sequential IDs */
const corpusArb = fc
  .integer({ min: 5, max: 30 })
  .chain((size) =>
    fc.tuple(...Array.from({ length: size }, (_, i) => siteRowArb(i + 1)))
  )
  .map((rows) => rows as unknown as SiteRow[]);

/** Generate a SurfParams object with optional filters */
const surfParamsArb: fc.Arbitrary<SurfParams> = fc.record({
  mood: fc.oneof(
    fc.constant(undefined),
    fc.constantFrom(...validMoods),
    fc.constant("surprise")
  ),
  character: fc.oneof(
    fc.constant(undefined),
    fc.constantFrom(...validCharacters)
  ),
  stacks: fc.oneof(
    fc.constant(undefined),
    fc.uniqueArray(fc.constantFrom(...validStacks), { minLength: 1, maxLength: 3 })
  ),
  hosts: fc.oneof(
    fc.constant(undefined),
    fc.uniqueArray(fc.constantFrom(...validHosts), { minLength: 1, maxLength: 3 })
  ),
  staticOrDynamic: fc.oneof(
    fc.constant(undefined),
    fc.constantFrom(...validStaticOrDynamic)
  ),
  seen: fc.constant(undefined),
});

// ---------------------------------------------------------------------------
// Mock D1 Database
// ---------------------------------------------------------------------------

/**
 * In-memory mock of D1Database that interprets the SQL generated by the
 * surf engine. The approach: instead of trying to parse SQL generically,
 * we replicate the same filtering logic the engine applies, using the
 * bindings in order.
 *
 * The surf engine generates SQL in a predictable pattern:
 * - First condition: nsfw = 0 (no binding)
 * - If mood: (mood_tags = ? OR mood_tags LIKE ? OR mood_tags LIKE ? OR mood_tags LIKE ?) — 4 bindings
 * - If character: character = ? — 1 binding
 * - If stacks: stack IN (?,?,...) — N bindings
 * - If hosts: host IN (?,?,...) — N bindings
 * - If staticOrDynamic: static_or_dynamic = ? — 1 binding
 * - vibecoded = 0 or vibecoded = 1 (literal, no binding)
 * - If tier filter in corner: built_with IN (?,?,...) — N bindings
 * - If unknown tiers: 1 = 0 (force no-match, no binding)
 * - Seen-list is inlined as integers, not bound: id NOT IN (1,2,3,...)
 */
function createMockD1(corpus: SiteRow[]): D1Database {
  function matchesMood(moodTags: string, mood: string): boolean {
    const tags = moodTags.split(";");
    return tags.includes(mood);
  }

  function filterSites(sql: string, bindings: unknown[]): SiteRow[] {
    // Force no-match condition
    if (sql.includes("1 = 0")) {
      return [];
    }

    // Determine which filters are active by examining the SQL
    const hasMoodFilter = sql.includes("mood_tags = ?");
    const hasCharFilter = sql.includes("character = ?");
    const hasStackFilter = sql.includes("stack IN");
    const hasHostFilter = sql.includes("host IN");
    const hasStaticDynFilter = /static_or_dynamic = \?/.test(sql);
    const hasBuiltWithFilter = sql.includes("built_with IN");

    // Vibecoded filter (literal in SQL, no binding)
    const requiresVibecoded1 = sql.includes("vibecoded = 1");
    const requiresVibecoded0 = sql.includes("vibecoded = 0");

    // Count stack placeholders
    let stackCount = 0;
    if (hasStackFilter) {
      const stackMatch = sql.match(/stack IN \(([^)]+)\)/);
      if (stackMatch) {
        stackCount = stackMatch[1].split(",").length;
      }
    }

    // Count host placeholders
    let hostCount = 0;
    if (hasHostFilter) {
      const hostMatch = sql.match(/host IN \(([^)]+)\)/);
      if (hostMatch) {
        hostCount = hostMatch[1].split(",").length;
      }
    }

    // Count built_with placeholders
    let builtWithCount = 0;
    if (hasBuiltWithFilter) {
      const builtWithMatch = sql.match(/built_with IN \(([^)]+)\)/);
      if (builtWithMatch) {
        builtWithCount = builtWithMatch[1].split(",").length;
      }
    }

    // Extract bindings in order
    let idx = 0;
    let moodValue: string | null = null;
    let characterValue: string | null = null;
    let stackValues: string[] = [];
    let hostValues: string[] = [];
    let staticDynValue: string | null = null;
    let builtWithValues: string[] = [];

    if (hasMoodFilter) {
      moodValue = bindings[idx] as string;
      idx += 4; // 4 bindings for mood pattern
    }
    if (hasCharFilter) {
      characterValue = bindings[idx] as string;
      idx += 1;
    }
    if (hasStackFilter) {
      stackValues = bindings.slice(idx, idx + stackCount) as string[];
      idx += stackCount;
    }
    if (hasHostFilter) {
      hostValues = bindings.slice(idx, idx + hostCount) as string[];
      idx += hostCount;
    }
    if (hasStaticDynFilter) {
      staticDynValue = bindings[idx] as string;
      idx += 1;
    }
    // vibecoded = 0/1 is literal — no binding consumed
    if (hasBuiltWithFilter) {
      builtWithValues = bindings.slice(idx, idx + builtWithCount) as string[];
      idx += builtWithCount;
    }

    // Extract inlined seen-list
    let seenIds: number[] = [];
    const notInMatch = sql.match(/id NOT IN \(([0-9,]+)\)/);
    if (notInMatch) {
      seenIds = notInMatch[1].split(",").map(Number);
    }

    return corpus.filter((site) => {
      // nsfw = 0
      if (site.nsfw !== 0) return false;

      // Vibecoded partition filter
      if (requiresVibecoded1 && site.vibecoded !== 1) return false;
      if (requiresVibecoded0 && site.vibecoded !== 0) return false;

      // Mood filter
      if (moodValue !== null) {
        if (!matchesMood(site.mood_tags, moodValue)) return false;
      }

      // Character filter
      if (characterValue !== null) {
        if (site.character !== characterValue) return false;
      }

      // Stack filter (OR within)
      if (stackValues.length > 0) {
        if (site.stack === null || !stackValues.includes(site.stack)) return false;
      }

      // Host filter (OR within)
      if (hostValues.length > 0) {
        if (site.host === null || !hostValues.includes(site.host)) return false;
      }

      // Static/dynamic filter
      if (staticDynValue !== null) {
        if (site.static_or_dynamic !== staticDynValue) return false;
      }

      // Built_with filter (tier expansion)
      if (builtWithValues.length > 0) {
        if (site.built_with === null || !builtWithValues.includes(site.built_with)) return false;
      }

      // Seen-list exclusion
      if (seenIds.length > 0) {
        if (seenIds.includes(site.id)) return false;
      }

      return true;
    });
  }

  const mockDb = {
    prepare(sql: string) {
      let boundBindings: unknown[] = [];
      return {
        bind(...args: unknown[]) {
          boundBindings = args;
          return {
            first<T>(): Promise<T | null> {
              if (sql.includes("COUNT(*)")) {
                const matches = filterSites(sql, boundBindings);
                return Promise.resolve({ cnt: matches.length } as T);
              }
              const matches = filterSites(sql, boundBindings);
              if (matches.length === 0) return Promise.resolve(null);
              // Simulate RANDOM() — pick random element
              const idx = Math.floor(Math.random() * matches.length);
              return Promise.resolve(matches[idx] as T);
            },
          };
        },
      };
    },
    dump: () => Promise.resolve(new ArrayBuffer(0)),
    batch: () => Promise.resolve([]),
    exec: () => Promise.resolve({ count: 0, duration: 0 }),
  } as unknown as D1Database;

  return mockDb;
}

// ---------------------------------------------------------------------------
// Helper: compute expected matching pool (ground truth for property checks)
// ---------------------------------------------------------------------------

function computeMatchingPool(corpus: SiteRow[], params: SurfParams): SiteRow[] {
  return corpus.filter((site) => {
    // NSFW exclusion
    if (site.nsfw !== 0) return false;

    // Vibecoded partition
    if (params.vibecoded) {
      if (site.vibecoded !== 1) return false;
    } else {
      if (site.vibecoded !== 0) return false;
    }

    // Mood filter (skip if absent or "surprise")
    if (params.mood && params.mood !== "surprise") {
      const tags = site.mood_tags.split(";");
      if (!tags.includes(params.mood)) return false;
    }

    // Character filter
    if (params.character) {
      if (site.character !== params.character) return false;
    }

    // Stack filter (OR within dimension)
    if (params.stacks && params.stacks.length > 0) {
      if (site.stack === null || !params.stacks.includes(site.stack)) return false;
    }

    // Host filter (OR within dimension)
    if (params.hosts && params.hosts.length > 0) {
      if (site.host === null || !params.hosts.includes(site.host)) return false;
    }

    // Static or dynamic filter
    if (params.staticOrDynamic) {
      if (site.static_or_dynamic !== params.staticOrDynamic) return false;
    }

    // Seen-list exclusion
    if (params.seen && params.seen.length > 0) {
      const validSeen = params.seen.filter((id) => Number.isInteger(id) && id > 0);
      if (validSeen.includes(site.id)) return false;
    }

    return true;
  });
}

// ---------------------------------------------------------------------------
// Property 1: Filter-matching
// Feature: mvp-stumble, Property 1: Surf returns only filter-matching sites
// ---------------------------------------------------------------------------

describe("Property 1: Filter-matching", () => {
  /**
   * **Validates: Requirements 1.1, 1.3, 2.2, 3.2, 4.2, 4.3**
   *
   * For any combination of active filters and any corpus state, every site
   * returned by the Surf Engine satisfies all active filter constraints.
   */
  it("returned site satisfies all active filter constraints", async () => {
    await fc.assert(
      fc.asyncProperty(corpusArb, surfParamsArb, async (corpus, params) => {
        const db = createMockD1(corpus);
        const result = await surf(db, params);

        if (result.status === "ok") {
          const site = result.site;

          // NSFW must be excluded
          expect(site.nsfw).toBe(0);

          // Mood filter check
          if (params.mood && params.mood !== "surprise") {
            const tags = site.mood_tags.split(";");
            expect(tags).toContain(params.mood);
          }

          // Character filter check
          if (params.character) {
            expect(site.character).toBe(params.character);
          }

          // Stack filter check (OR within dimension)
          if (params.stacks && params.stacks.length > 0) {
            expect(params.stacks).toContain(site.stack);
          }

          // Host filter check (OR within dimension)
          if (params.hosts && params.hosts.length > 0) {
            expect(params.hosts).toContain(site.host);
          }

          // Static or dynamic filter check
          if (params.staticOrDynamic) {
            expect(site.static_or_dynamic).toBe(params.staticOrDynamic);
          }

          // Seen-list check
          if (params.seen && params.seen.length > 0) {
            const validSeen = params.seen.filter(
              (id) => Number.isInteger(id) && id > 0
            );
            expect(validSeen).not.toContain(site.id);
          }
        }
      }),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 2: NSFW exclusion
// Feature: mvp-stumble, Property 2: NSFW sites are never returned
// ---------------------------------------------------------------------------

describe("Property 2: NSFW exclusion", () => {
  /**
   * **Validates: Requirements 12.1, 12.2**
   *
   * For any surf request regardless of filters, the Surf Engine
   * never returns a site whose nsfw value is 1 (true).
   */
  it("NSFW sites are never returned regardless of filters", async () => {
    // Generate corpora where at least some sites are NSFW
    const nsfwCorpusArb = fc
      .integer({ min: 5, max: 20 })
      .chain((size) =>
        fc.tuple(
          ...Array.from({ length: size }, (_, i) =>
            fc.record({
              id: fc.constant(i + 1),
              url: fc.constant(`https://site-${i + 1}.example.com`),
              title: fc.constant(`Site ${i + 1}`),
              mood_tags: moodTagsArb,
              character: fc.constantFrom(...validCharacters),
              stack: nullableStackArb,
              host: nullableHostArb,
              static_or_dynamic: nullableStaticOrDynamicArb,
              built_with: fc.constant(null),
              why_note: fc.constant("A cool site"),
              nsfw: fc.constantFrom(0, 1) as fc.Arbitrary<number>, // 50% NSFW
              vibecoded: fc.constant(0),
              source: fc.constant("manual"),
              tier: fc.constant("featured"),
              added_at: fc.constant("2024-01-01T00:00:00.000Z"),
            })
          )
        )
      )
      .map((rows) => rows as unknown as SiteRow[]);

    await fc.assert(
      fc.asyncProperty(nsfwCorpusArb, surfParamsArb, async (corpus, params) => {
        const db = createMockD1(corpus);
        const result = await surf(db, params);

        if (result.status === "ok") {
          expect(result.site.nsfw).toBe(0);
        }
      }),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 3: Seen-list exclusion
// Feature: mvp-stumble, Property 3: Seen-list exclusion
// ---------------------------------------------------------------------------

describe("Property 3: Seen-list exclusion", () => {
  /**
   * **Validates: Requirements 10.5**
   *
   * For any surf request containing a seen-list of site IDs, the Surf
   * Engine never returns a site whose ID appears in the seen-list.
   */
  it("returned site ID never appears in seen-list", async () => {
    const seenParamsArb = fc.record({
      mood: fc.constant(undefined),
      character: fc.constant(undefined),
      stacks: fc.constant(undefined),
      hosts: fc.constant(undefined),
      staticOrDynamic: fc.constant(undefined),
      seen: fc.constant(undefined), // placeholder, set dynamically
    });

    await fc.assert(
      fc.asyncProperty(corpusArb, fc.integer({ min: 1, max: 4 }), async (corpus, seenCount) => {
        // Pick a subset of IDs as the seen-list (not all, so some remain)
        const nonNsfw = corpus.filter((s) => s.nsfw === 0);
        if (nonNsfw.length <= 1) return; // Skip trivial corpora

        const actualSeenCount = Math.min(seenCount, nonNsfw.length - 1);
        const seen = nonNsfw.slice(0, actualSeenCount).map((s) => s.id);

        const params: SurfParams = { seen };
        const db = createMockD1(corpus);
        const result = await surf(db, params);

        if (result.status === "ok") {
          expect(seen).not.toContain(result.site.id);
        }
      }),
      { numRuns: 100 }
    );
  });

  it("seen-list with all matching IDs returns exhausted", async () => {
    await fc.assert(
      fc.asyncProperty(corpusArb, async (corpus) => {
        // Seen all non-NSFW sites
        const nonNsfw = corpus.filter((s) => s.nsfw === 0);
        if (nonNsfw.length === 0) return; // Skip if all NSFW

        const seen = nonNsfw.map((s) => s.id);
        const params: SurfParams = { seen };
        const db = createMockD1(corpus);
        const result = await surf(db, params);

        expect(result.status).toBe("exhausted");
      }),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 4: Mood filter semicolon parsing
// Feature: mvp-stumble, Property 4: Mood filter matches semicolon-separated tags
// ---------------------------------------------------------------------------

describe("Property 4: Mood filter semicolon parsing", () => {
  /**
   * **Validates: Requirements 2.2**
   *
   * For any mood value and any site returned, the site's mood_tags field
   * contains that mood as a complete semicolon-separated entry (no substring
   * false positives).
   */
  it("mood LIKE patterns match correctly, no substring false positives", async () => {
    await fc.assert(
      fc.asyncProperty(
        corpusArb,
        fc.constantFrom(...validMoods),
        async (corpus, mood) => {
          const params: SurfParams = { mood };
          const db = createMockD1(corpus);
          const result = await surf(db, params);

          if (result.status === "ok") {
            const tags = result.site.mood_tags.split(";");
            // The mood must appear as an exact entry, not a substring
            expect(tags).toContain(mood);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it("mood filter does not match partial tags", async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.constantFrom(...validMoods),
        async (mood) => {
          // Create a corpus with one site that HAS the mood and one that doesn't
          const siteWithMood: SiteRow = {
            id: 1,
            url: "https://has-mood.example.com",
            title: "Has Mood",
            mood_tags: mood,
            character: "modern_indie",
            stack: null,
            host: null,
            static_or_dynamic: null,
            built_with: null,
            why_note: "test",
            nsfw: 0,
            vibecoded: 0,
            source: "manual",
            tier: "featured",
            added_at: "2024-01-01T00:00:00.000Z",
          };

          // Pick a different mood for the second site
          const otherMoods = validMoods.filter((m) => m !== mood);
          const siteWithoutMood: SiteRow = {
            id: 2,
            url: "https://no-mood.example.com",
            title: "No Mood",
            mood_tags: otherMoods[0],
            character: "modern_indie",
            stack: null,
            host: null,
            static_or_dynamic: null,
            built_with: null,
            why_note: "test",
            nsfw: 0,
            vibecoded: 0,
            source: "manual",
            tier: "featured",
            added_at: "2024-01-01T00:00:00.000Z",
          };

          const corpus = [siteWithMood, siteWithoutMood];
          const db = createMockD1(corpus);
          const params: SurfParams = { mood };
          const result = await surf(db, params);

          if (result.status === "ok") {
            // Must be the site WITH the mood
            const tags = result.site.mood_tags.split(";");
            expect(tags).toContain(mood);
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 5: Surprise equivalence
// Feature: mvp-stumble, Property 5: Surprise and absent mood are equivalent
// ---------------------------------------------------------------------------

describe("Property 5: Surprise equivalence", () => {
  /**
   * **Validates: Requirements 2.3, 2.4**
   *
   * The candidate pool when mood=surprise is identical to the candidate pool
   * when mood is omitted entirely.
   */
  it("mood=surprise produces same pool as mood absent", async () => {
    await fc.assert(
      fc.asyncProperty(corpusArb, surfParamsArb, async (corpus, baseParams) => {
        // Compute pools using the ground-truth helper
        const paramsWithSurprise: SurfParams = {
          ...baseParams,
          mood: "surprise",
        };
        const paramsWithoutMood: SurfParams = {
          ...baseParams,
          mood: undefined,
        };

        const poolSurprise = computeMatchingPool(corpus, paramsWithSurprise);
        const poolNoMood = computeMatchingPool(corpus, paramsWithoutMood);

        // Both pools must contain the same sites
        const idsSurprise = poolSurprise.map((s) => s.id).sort();
        const idsNoMood = poolNoMood.map((s) => s.id).sort();
        expect(idsSurprise).toEqual(idsNoMood);

        // Also verify via the engine: if surprise returns a site, it should
        // be in the no-mood pool
        const db = createMockD1(corpus);
        const result = await surf(db, paramsWithSurprise);
        if (result.status === "ok") {
          const noMoodIds = poolNoMood.map((s) => s.id);
          expect(noMoodIds).toContain(result.site.id);
        }
      }),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 6: Build filter OR-within-AND-across
// Feature: mvp-stumble, Property 6: Build filter OR-within-AND-across dimensions
// ---------------------------------------------------------------------------

describe("Property 6: Build filter OR-within-AND-across dimensions", () => {
  /**
   * **Validates: Requirements 4.2, 4.3**
   *
   * Multi-value within the same dimension uses OR; across dimensions uses AND.
   */
  it("multi-value within dimension uses OR, across dimensions uses AND", async () => {
    await fc.assert(
      fc.asyncProperty(
        corpusArb,
        fc.uniqueArray(fc.constantFrom(...validStacks), { minLength: 1, maxLength: 3 }),
        fc.uniqueArray(fc.constantFrom(...validHosts), { minLength: 1, maxLength: 3 }),
        async (corpus, stacks, hosts) => {
          const params: SurfParams = { stacks, hosts };
          const db = createMockD1(corpus);
          const result = await surf(db, params);

          if (result.status === "ok") {
            const site = result.site;

            // OR within stacks: site.stack must be one of the selected stacks
            expect(stacks).toContain(site.stack);

            // OR within hosts: site.host must be one of the selected hosts
            expect(hosts).toContain(site.host);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it("single dimension filter with multiple values uses OR", async () => {
    await fc.assert(
      fc.asyncProperty(
        corpusArb,
        fc.uniqueArray(fc.constantFrom(...validStacks), { minLength: 2, maxLength: 4 }),
        async (corpus, stacks) => {
          const params: SurfParams = { stacks };
          const db = createMockD1(corpus);
          const result = await surf(db, params);

          if (result.status === "ok") {
            // The returned site's stack must be one of the selected values
            expect(stacks).toContain(result.site.stack);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it("AND across dimensions: mood + character + build all satisfied", async () => {
    await fc.assert(
      fc.asyncProperty(
        corpusArb,
        fc.constantFrom(...validMoods),
        fc.constantFrom(...validCharacters),
        fc.uniqueArray(fc.constantFrom(...validStacks), { minLength: 1, maxLength: 2 }),
        async (corpus, mood, character, stacks) => {
          const params: SurfParams = { mood, character, stacks };
          const db = createMockD1(corpus);
          const result = await surf(db, params);

          if (result.status === "ok") {
            const site = result.site;
            const tags = site.mood_tags.split(";");
            expect(tags).toContain(mood);
            expect(site.character).toBe(character);
            expect(stacks).toContain(site.stack);
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Property 7: Zero-match vs exhausted distinction
// Feature: mvp-stumble, Property 7: Zero-match vs exhausted distinction
// ---------------------------------------------------------------------------

describe("Property 7: Zero-match vs exhausted distinction", () => {
  /**
   * **Validates: Requirements 1.4, 10.6, 11.1**
   *
   * Correct status based on pool state:
   * - no_match: no non-NSFW sites match the filters (ignoring seen-list)
   * - exhausted: sites match but all have been seen
   */
  it("returns no_match when no sites match filters (ignoring seen-list)", async () => {
    await fc.assert(
      fc.asyncProperty(corpusArb, async (corpus) => {
        // Use a character that no site has — force all sites to one char, filter for another
        const allModernIndie = corpus.map((s) => ({
          ...s,
          character: "modern_indie" as const,
          nsfw: 0,
        }));
        const params: SurfParams = { character: "old_web" };
        const db = createMockD1(allModernIndie);
        const result = await surf(db, params);

        expect(result.status).toBe("no_match");
      }),
      { numRuns: 100 }
    );
  });

  it("returns exhausted when all matching sites are in seen-list", async () => {
    await fc.assert(
      fc.asyncProperty(corpusArb, async (corpus) => {
        // Make all sites non-NSFW and same character for predictability
        const safeSites = corpus.map((s) => ({
          ...s,
          nsfw: 0,
          character: "modern_indie" as const,
        }));
        const matchingIds = safeSites.map((s) => s.id);

        const params: SurfParams = {
          character: "modern_indie",
          seen: matchingIds,
        };
        const db = createMockD1(safeSites);
        const result = await surf(db, params);

        expect(result.status).toBe("exhausted");
      }),
      { numRuns: 100 }
    );
  });

  it("no_match and exhausted are mutually exclusive", async () => {
    await fc.assert(
      fc.asyncProperty(corpusArb, surfParamsArb, async (corpus, params) => {
        const db = createMockD1(corpus);
        const result = await surf(db, params);

        // Can only be one status
        const statuses = ["ok", "no_match", "exhausted"];
        expect(statuses).toContain(result.status);

        // Verify the distinction:
        const poolWithoutSeen = computeMatchingPool(corpus, {
          ...params,
          seen: undefined,
        });
        const poolWithSeen = computeMatchingPool(corpus, params);

        if (poolWithoutSeen.length === 0) {
          // No sites match → must be no_match
          expect(result.status).not.toBe("exhausted");
          if (result.status !== "ok") {
            expect(result.status).toBe("no_match");
          }
        } else if (poolWithSeen.length === 0 && poolWithoutSeen.length > 0) {
          // Sites match but all seen → must be exhausted
          expect(result.status).toBe("exhausted");
        } else if (poolWithSeen.length > 0) {
          // Sites available → must be ok
          expect(result.status).toBe("ok");
        }
      }),
      { numRuns: 100 }
    );
  });
});


// ---------------------------------------------------------------------------
// Vibecoded Corner — Engine Tests (Task 3.4)
// Feature: vibecoded-corner, Validates: Requirements 12.1
// ---------------------------------------------------------------------------

/** Built_with values by tier for corner site generators */
const t2BuiltWith = ["lovable", "v0", "bolt", "replit"] as const;
const t3BuiltWith = ["claude_code", "cursor", "kiro", "github_copilot"] as const;
const t4BuiltWith = ["cloudflare_workers", "fly"] as const;
const allCornerBuiltWith = [...t2BuiltWith, ...t3BuiltWith, ...t4BuiltWith] as const;

/** Generate a vibecoded=1 site row with a valid built_with value */
const cornerSiteRowArb = (id: number): fc.Arbitrary<SiteRow> =>
  fc.record({
    id: fc.constant(id),
    url: fc.constant(`https://corner-${id}.example.com`),
    title: fc.constant(`Corner Site ${id}`),
    mood_tags: moodTagsArb,
    character: fc.constantFrom(...validCharacters),
    stack: nullableStackArb,
    host: nullableHostArb,
    static_or_dynamic: nullableStaticOrDynamicArb,
    built_with: fc.constantFrom(...allCornerBuiltWith) as fc.Arbitrary<string | null>,
    why_note: fc.constant("An AI-built site"),
    nsfw: fc.constant(0),
    vibecoded: fc.constant(1),
    source: fc.constant("manual"),
    tier: fc.constant("featured"),
    added_at: fc.constant("2024-01-01T00:00:00.000Z"),
  });

/** Generate a mixed corpus with both open-web (vibecoded=0) and corner (vibecoded=1) sites */
const mixedCorpusArb = fc
  .tuple(
    fc.integer({ min: 3, max: 10 }),
    fc.integer({ min: 3, max: 10 })
  )
  .chain(([openCount, cornerCount]) =>
    fc.tuple(
      fc.tuple(...Array.from({ length: openCount }, (_, i) => siteRowArb(i + 1))),
      fc.tuple(...Array.from({ length: cornerCount }, (_, i) => cornerSiteRowArb(openCount + i + 1)))
    )
  )
  .map(([openRows, cornerRows]) => [
    ...(openRows as unknown as SiteRow[]),
    ...(cornerRows as unknown as SiteRow[]),
  ]);

// ---------------------------------------------------------------------------
// Test: Default surf (no vibecoded param) excludes vibecoded=1 rows
// ---------------------------------------------------------------------------

describe("Vibecoded Corner: Default surf excludes vibecoded=1 rows", () => {
  /**
   * **Validates: Requirements 12.1**
   *
   * When the vibecoded param is absent (default open-web surf),
   * the engine only returns sites with vibecoded=0 — corner sites are excluded.
   */
  it("surf without vibecoded param never returns vibecoded=1 rows", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const db = createMockD1(corpus);
        const result = await surf(db, {}); // No vibecoded param

        if (result.status === "ok") {
          expect(result.site.vibecoded).toBe(0);
        }
      }),
      { numRuns: 100 }
    );
  });

  it("surf with vibecoded=false never returns vibecoded=1 rows", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const db = createMockD1(corpus);
        const result = await surf(db, { vibecoded: false });

        if (result.status === "ok") {
          expect(result.site.vibecoded).toBe(0);
        }
      }),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Test: Corner mode (vibecoded=true) returns only vibecoded=1 rows
// ---------------------------------------------------------------------------

describe("Vibecoded Corner: Corner mode returns only vibecoded=1 rows", () => {
  /**
   * **Validates: Requirements 12.1**
   *
   * When vibecoded=true, the engine only returns sites with vibecoded=1.
   */
  it("surf with vibecoded=true only returns vibecoded=1 rows", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const db = createMockD1(corpus);
        const result = await surf(db, { vibecoded: true });

        if (result.status === "ok") {
          expect(result.site.vibecoded).toBe(1);
          expect(result.site.built_with).not.toBeNull();
        }
      }),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Test: tier=[2] in corner returns only T2 built_with rows
// ---------------------------------------------------------------------------

describe("Vibecoded Corner: Tier filter narrows within corner", () => {
  /**
   * **Validates: Requirements 12.1**
   *
   * When tier=[2] is active in corner mode, only sites whose built_with
   * maps to tier 2 are returned.
   */
  it("tier=[2] returns only T2 built_with values", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const db = createMockD1(corpus);
        const result = await surf(db, { vibecoded: true, tiers: [2] });

        if (result.status === "ok") {
          expect(result.site.vibecoded).toBe(1);
          expect(t2BuiltWith as readonly string[]).toContain(result.site.built_with);
        }
      }),
      { numRuns: 100 }
    );
  });

  it("tier=[3] returns only T3 built_with values", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const db = createMockD1(corpus);
        const result = await surf(db, { vibecoded: true, tiers: [3] });

        if (result.status === "ok") {
          expect(result.site.vibecoded).toBe(1);
          expect(t3BuiltWith as readonly string[]).toContain(result.site.built_with);
        }
      }),
      { numRuns: 100 }
    );
  });

  it("tier=[2,3] returns only T2 or T3 built_with values", async () => {
    const t2t3 = [...t2BuiltWith, ...t3BuiltWith];
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const db = createMockD1(corpus);
        const result = await surf(db, { vibecoded: true, tiers: [2, 3] });

        if (result.status === "ok") {
          expect(result.site.vibecoded).toBe(1);
          expect(t2t3 as string[]).toContain(result.site.built_with);
        }
      }),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Test: tier=[4] in corner with no T4 rows returns no_match
// ---------------------------------------------------------------------------

describe("Vibecoded Corner: Tier with no matching rows returns no_match", () => {
  /**
   * **Validates: Requirements 12.1**
   *
   * When filtering by a tier that has no sites in the corner pool,
   * the engine returns no_match.
   */
  it("tier=[4] with only T2 corner sites returns no_match", async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.integer({ min: 3, max: 8 }),
        async (openCount) => {
          // Build a corpus with open-web sites and T2-only corner sites (no T4)
          const openSites: SiteRow[] = Array.from({ length: openCount }, (_, i) => ({
            id: i + 1,
            url: `https://open-${i + 1}.example.com`,
            title: `Open Site ${i + 1}`,
            mood_tags: "useful",
            character: "modern_indie" as const,
            stack: null,
            host: null,
            static_or_dynamic: null,
            built_with: null,
            why_note: "A site",
            nsfw: 0,
            vibecoded: 0,
            source: "manual",
            tier: "featured",
            added_at: "2024-01-01T00:00:00.000Z",
          }));

          const cornerSites: SiteRow[] = [
            {
              id: openCount + 1,
              url: "https://lovable-app.example.com",
              title: "Lovable App",
              mood_tags: "useful",
              character: "modern_indie",
              stack: "nextjs",
              host: "vercel",
              static_or_dynamic: "dynamic",
              built_with: "lovable",
              why_note: "Built with Lovable",
              nsfw: 0,
              vibecoded: 1,
              source: "manual",
              tier: "featured",
              added_at: "2024-01-01T00:00:00.000Z",
            },
            {
              id: openCount + 2,
              url: "https://bolt-app.example.com",
              title: "Bolt App",
              mood_tags: "learn",
              character: "modern_indie",
              stack: null,
              host: "netlify",
              static_or_dynamic: "static",
              built_with: "bolt",
              why_note: "Built with Bolt",
              nsfw: 0,
              vibecoded: 1,
              source: "manual",
              tier: "featured",
              added_at: "2024-01-01T00:00:00.000Z",
            },
          ];

          const corpus = [...openSites, ...cornerSites];
          const db = createMockD1(corpus);
          const result = await surf(db, { vibecoded: true, tiers: [4] });

          // No T4 sites exist — should be no_match
          expect(result.status).toBe("no_match");
        }
      ),
      { numRuns: 50 }
    );
  });

  it("tier=[99] (unknown) returns no_match due to 1=0 fallback", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const db = createMockD1(corpus);
        const result = await surf(db, { vibecoded: true, tiers: [99] });

        // Unknown tier → expandTiers returns [] → 1=0 → no_match
        expect(result.status).toBe("no_match");
      }),
      { numRuns: 50 }
    );
  });
});

// ---------------------------------------------------------------------------
// Test: Seen-list exhausts the corner pool → returns exhausted
// ---------------------------------------------------------------------------

describe("Vibecoded Corner: Seen-list exhaustion", () => {
  /**
   * **Validates: Requirements 12.1**
   *
   * When all corner sites have been seen, the engine returns exhausted
   * (not no_match, since the pool exists).
   */
  it("seen-list containing all corner IDs returns exhausted", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        // Mark all corner sites as seen
        const cornerIds = corpus
          .filter((s) => s.vibecoded === 1 && s.nsfw === 0)
          .map((s) => s.id);

        if (cornerIds.length === 0) return; // Skip if no corner sites

        const db = createMockD1(corpus);
        const result = await surf(db, { vibecoded: true, seen: cornerIds });

        expect(result.status).toBe("exhausted");
      }),
      { numRuns: 100 }
    );
  });

  it("seen-list with some corner IDs still returns ok for unseen sites", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const cornerSites = corpus.filter((s) => s.vibecoded === 1 && s.nsfw === 0);
        if (cornerSites.length <= 1) return; // Need at least 2 to see some but not all

        // See only the first corner site
        const seen = [cornerSites[0].id];

        const db = createMockD1(corpus);
        const result = await surf(db, { vibecoded: true, seen });

        if (result.status === "ok") {
          expect(result.site.vibecoded).toBe(1);
          expect(seen).not.toContain(result.site.id);
        }
      }),
      { numRuns: 100 }
    );
  });
});

// ---------------------------------------------------------------------------
// Test: Existing open-web seen/no_match/exhausted still work with vibecoded=0
// ---------------------------------------------------------------------------

describe("Vibecoded Corner: Open-web behaviour preserved", () => {
  /**
   * **Validates: Requirements 12.1**
   *
   * The existing open-web surf behaviours (seen-list, no_match, exhausted)
   * are unaffected by the vibecoded partition.
   */
  it("open-web surf with all IDs seen returns exhausted", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const openIds = corpus
          .filter((s) => s.vibecoded === 0 && s.nsfw === 0)
          .map((s) => s.id);

        if (openIds.length === 0) return;

        const db = createMockD1(corpus);
        const result = await surf(db, { seen: openIds });

        expect(result.status).toBe("exhausted");
      }),
      { numRuns: 100 }
    );
  });

  it("open-web surf with impossible filter returns no_match", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        // Force all open-web sites to one character, filter for another
        const tweaked = corpus.map((s) =>
          s.vibecoded === 0 ? { ...s, character: "modern_indie" } : s
        );
        const db = createMockD1(tweaked);
        const result = await surf(db, { character: "old_web" });

        expect(result.status).toBe("no_match");
      }),
      { numRuns: 100 }
    );
  });

  it("open-web seen-list exclusion still works in mixed corpus", async () => {
    await fc.assert(
      fc.asyncProperty(mixedCorpusArb, async (corpus) => {
        const openSites = corpus.filter((s) => s.vibecoded === 0 && s.nsfw === 0);
        if (openSites.length <= 1) return;

        // See only the first open-web site
        const seen = [openSites[0].id];

        const db = createMockD1(corpus);
        const result = await surf(db, { seen });

        if (result.status === "ok") {
          expect(result.site.vibecoded).toBe(0);
          expect(seen).not.toContain(result.site.id);
        }
      }),
      { numRuns: 100 }
    );
  });

  it("corner sites never leak into open-web results in mixed corpus", async () => {
    await fc.assert(
      fc.asyncProperty(
        mixedCorpusArb,
        surfParamsArb,
        async (corpus, params) => {
          // Ensure no vibecoded param (open-web mode)
          const openParams = { ...params, vibecoded: undefined, tiers: undefined };
          const db = createMockD1(corpus);
          const result = await surf(db, openParams);

          if (result.status === "ok") {
            expect(result.site.vibecoded).toBe(0);
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});
