/**
 * Gloss map — the single source of the TUNING menu's plain-English copy.
 *
 * - GROUP_GLOSS: the short line under each filter group label.
 * - CHIP_GLOSS: the info-strip explanation for one chip (keyed by chip value;
 *   tier chips keyed by tier number as a string).
 * - RECIPE_FRAGMENTS: per-value phrases composed into the open-web card's
 *   "the recipe: …" line.
 *
 * All copy is APPROVED verbatim (Final Cut reviews 1–10, design §1.4 & §2.4).
 * DOM-free — safe to import anywhere on the client.
 */

// FINAL — group glosses (verbatim)
export const GROUP_GLOSS: Record<string, string> = {
  character: "what kind of place it is",
  stack: "what it was built with",
  host: "where it lives online",
  static_or_dynamic: "does it change while you watch",
  tier: "how much of it AI built",
};

// CHIP_GLOSS: APPROVED verbatim (review 2). Tier glosses reuse the ladder
// descriptions (§4.3) — the OSD corner-mode tier chips and the ladder read alike.
export const CHIP_GLOSS: Record<string, string> = {
  // character
  modern_indie: "hand-made, but built this decade",
  old_web: "genuine survivors from the early internet",
  retro_personal: "new sites in old clothes",
  minimal_static: "plain, fast, nothing extra",
  // stack
  astro: "builder that ships mostly plain pages",
  gatsby: "React-based site builder",
  ghost: "publishing platform for writers",
  hugo: "a very fast static-site builder",
  jekyll: "the classic blog builder",
  nextjs: "React framework for full apps",
  nuxt: "Vue framework for full apps",
  react_spa: "one page, JavaScript does everything",
  static_html: "written by hand, no tools",
  sveltekit: "Svelte framework, lean and quick",
  wordpress: "runs a third of the web",
  // host
  aws_s3: "Amazon's plain file storage",
  fly: "runs apps near the visitor",
  github_pages: "free hosting from code repos",
  netlify: "push code, site goes live",
  render: "simple hosting for full apps",
  vercel: "hosting built for web frameworks",
  // type
  static: "pre-made pages, served as-is",
  dynamic: "built fresh on each visit",
  // tier (corner mode) — keyed by tier number as string; reuse ladder descriptions
  "1": "describe a site in a sentence, get a site",
  "2": "sketch screens and logic, AI wires it up",
  "3": "you steer, an AI pair-codes with you",
  "4": "spec it, and agents build it — this site's own recipe",
};

// APPROVED verbatim (review 5). stack fragment + host fragment.
export const RECIPE_FRAGMENTS: Record<string, string> = {
  // stack
  static_html: "written by hand, no tools",
  hugo: "generated by Hugo, a fast site builder",
  jekyll: "generated by Jekyll, the classic blog builder",
  astro: "built with Astro, shipping mostly plain pages",
  gatsby: "built with Gatsby, a React site builder",
  nextjs: "built with Next.js, a React app framework",
  nuxt: "built with Nuxt, a Vue app framework",
  react_spa: "a single React page — JavaScript does everything",
  sveltekit: "built with SvelteKit, lean and quick",
  wordpress: "run on WordPress, like a third of the web",
  ghost: "published with Ghost, a writers' platform",
  // host
  github_pages: "hosted free from a code repo",
  netlify: "push code, site goes live",
  vercel: "hosted on Vercel, built for frameworks",
  aws_s3: "served from Amazon's plain file storage",
  render: "hosted on Render",
  fly: "running on Fly.io, near its visitors",
};
